### ISSUE TITLE
Tailscale MagicDNS subnet routes are not found

### ISSUE THREAD

**Issue by uchouhan** [aspiredu/heroku-tailscale-buildpack#14]
It seems like the `TAILSCALE_ACCEPT_ROUTES` defaults to `true`.

We're using `4via6` routing that should give us unique DNS hostnames for every device in the subnet. However we're not able to reach those DNS hostnames from the Heroku server that has the buildpack installed. We've verified that the server is connected to the `tailnet` and can indeed reach the `tailscale` IPv4 IP but just not the subnet magicDNS routes.

For example:
```
socks5: client connection failed: lookup 192-168-1-115-via-1 on 10.1.0.2:53: no such host
```

**Comment by tim-schilling** [comment]
What does `tailscale status` return from a heroku dyno?

**Comment by uchouhan** [comment]
It shows the active hosts, and there some health check errors in the comments

```
~ $ tailscale status
1xx.x6.x7.x5    6xxx-run-wqaq7n user1@       linux   -
1xx.x9.9.x8    6xxx-web-1-wqaq7n user1@       linux   -
1xx.1xx.3.1xx   routerpie          user1@       linux   -

# Health check:
#     - dns-os: getting OS base config is not supported
#     - dns: getting OS base config is not supported
```

**Comment by tim-schilling** [comment]
Ah, right. I have run into this. It's been a minute. I haven't been able to determine why, but I've only been able to connect to machines based on their IP addresses.

**Comment by uchouhan** [comment]
not seeing any name servers for the Tailscale network in `/etc/resolv.conf`, could that be an issue?

```
~ $ cat /etc/resolv.conf 
[proxychains] DLL init: proxychains-ng 4.16
# This file is managed by man:systemd-resolved(8). Do not edit.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs must not access this file directly, but only through the
# symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a different way,
# replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 10.1.0.2
search ec2.internal
```

**Comment by uchouhan** [comment]
would adding a `localnet` to the proxy chains config work? if it does, not sure if this can be an envvar or if we'd have to fork and maintain a separate repo with our custom proxy chains config

```
## Tailscale Subnet
localnet 100.x.x.x/10
```

**Comment by tim-schilling** [comment]
I don't know, but you can customize the proxychains config [as per the docs here](https://github.com/aspiredu/heroku-tailscale-buildpack#customizing-proxychainsconf)

**Comment by uchouhan** [comment]
that worked!

**Comment by tim-schilling** [comment]
Do you mind explaining why that worked? Regarding the localnet addition.

**Comment by uchouhan** [comment]
yes, that line excludes the Tailscale DNS requests from being proxied

**Comment by tim-schilling** [comment]
Oh my goodness... That was a major problem for me but I didn't consider that as an issue. I think you just shaved off a fair amount of work on my part reimplementing/working around the magicdns failure.

**Comment by uchouhan** [comment]
let me know if it works for you! I think it worked for me momentarily and does not seem to be working again

**Comment by tim-schilling** [comment]
I had to write some logic to maintain the certificate between runs of a dyno due to LetsEncrypt's rate-limiting of certificates for a domain.
